name: Default Workflow

on: [pull_request, push]

jobs:
  default-job:
    name: Default Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Print Context Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.GITHUB_WORKFLOW }}"
          echo "Event: ${{ github.GITHUB_EVENT_NAME }}"
          
          echo "Runner"
          echo '\t' "Name: ${{ runner.name }}"
          echo '\t' "OS: ${{ runner.os }}"
          echo '\t' "ArchitectureOS: ${{ runner.arch }}"
          
          echo "Run ID: ${{ env.GITHUB_RUN_ID }}"
          echo "Run Number: ${{ env.GITHUB_RUN_NUMBER }}"
