name: Default Workflow

on: [pull_request, push]

jobs:
  default-job:
    name: Default Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Print Context Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Event: ${{ github.event_name }}"
          
          echo "Runner"
          echo "- Name: ${{ runner.name }}"
          echo "- OS: ${{ runner.os }}"
          echo "- ArchitectureOS: ${{ runner.arch }}"

          echo "Run"
          echo "- ID: ${{ env.run_id }}"
          echo "- Number: ${{ env.run_number }}"
