name: Default Workflow

on: [pull_request, push, workflow_dispatch]

jobs:
  default-job:
    name: Default Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Print Main Contexts Variables
        run: |
          echo "Event"
          echo "- Name: ${{ github.event_name }}"

          echo
          echo "Repository"
          echo "- Name: ${{ github.repository }}"
          echo "- Url: ${{ github.repositoryUrl }}"
          
          echo
          echo "Workflow"
          echo "- Name: ${{ github.workflow }}"
          echo "- Path: ${{ github.workflow_ref }}"
          echo "- Retention: ${{ github.retention_days }}"
          
          echo
          echo "Runner"
          echo "- Name: ${{ runner.name }}"
          echo "- OS: ${{ runner.os }}"
          echo "- Architecture: ${{ runner.arch }}"

          echo
          echo "Run"
          echo "- ID: ${{ github.run_id }}"
          echo "- Number: ${{ github.run_number }}"
